#!/usr/bin/perl -w


open(SUB, "/home/ai/./strn |");

while ($data = <SUB>) {

print "$data";

system("echo 'cmd_5($data)' > /dev/ttyS2 ");
#system("mosquitto_pub -h 192.168.168.150 -t '/ai/station' -m '$data'"); #enable for MQTT screens
}

