#!/usr/bin/perl -w


open(SUB, "tail -f /var/log/mycroft/voice.log  |  grep -oiP --line-buffered '(?<=__main__:handle_record_end:)[[:digit:]]+' |");

while ($data = <SUB>) {
 
#print "cmd_3(off)";
print "$data";

system('echo "cmd_3($data)" > /dev/ttyS2 ');
#system("mosquitto_pub -h 192.168.168.150 -t '/ai/offlight' -m '$data'"); enable for MQTT screens
}




